"""
Domain-grouped views for operations.

urls.py imports from here: from . import views
"""
from operations.views.billing import statement_detail, statements_list
from operations.views.business import business_settings
from operations.views.customers import (
    add_vaccination,
    advance_pipeline,
    client_add_dog,
    client_create,
    client_detail,
    client_edit,
    client_list,
    client_vcard,
    contact_import_preview,
    contact_import_selected,
    contact_sync,
    customer_add_dog,
    customer_detail,
    customer_edit,
    dog_delete,
    dog_detail,
    dog_edit,
    dog_vaccinations,
    update_coi,
    validate_vaccination,
)
from operations.views.scheduling import (
    approve_pending_event,
    dashboard,
    duplicate_visit,
    ical_feed,
    mobile_checkin,
    parse_datetime_field,
    pending_events,
    reject_pending_event,
    visit_check_in,
    visit_check_out,
    visit_create,
    visit_delete,
    visit_edit,
    visit_timeline,
    visit_timeline_forward,
)

__all__ = [
    'business_settings',
    'add_vaccination',
    'advance_pipeline',
    'approve_pending_event',
    'client_add_dog',
    'client_create',
    'client_detail',
    'client_edit',
    'client_list',
    'client_vcard',
    'contact_import_preview',
    'contact_import_selected',
    'contact_sync',
    'customer_add_dog',
    'customer_detail',
    'customer_edit',
    'dashboard',
    'dog_delete',
    'dog_detail',
    'dog_edit',
    'dog_vaccinations',
    'duplicate_visit',
    'ical_feed',
    'mobile_checkin',
    'parse_datetime_field',
    'pending_events',
    'reject_pending_event',
    'statement_detail',
    'statements_list',
    'update_coi',
    'validate_vaccination',
    'visit_check_in',
    'visit_check_out',
    'visit_create',
    'visit_delete',
    'visit_edit',
    'visit_timeline',
    'visit_timeline_forward',
]