"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ved=(!vnu2_0)6(%lt%m_@8mku@3*jj_iix@%5f&p*(fw_)h@n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.ngrok-free.app',
    '.ngrok-free.dev',
    '.ngrok.io',
]

CSRF_TRUSTED_ORIGINS = [
    'https://127.0.0.1:9000',
    'https://localhost:9000',
]

# ngrok terminates TLS and forwards X-Forwarded-Proto: https
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'operations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'operations.middleware.NgrokCsrfMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'operations' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Gmail OAuth — credentials and token live in O-Auth Key/ (see oauth_setup.py).
GMAIL_OAUTH_DIR = Path(os.environ.get('GMAIL_OAUTH_DIR', BASE_DIR / 'O-Auth Key'))
# Optional From header — only set if it matches your authenticated Gmail / send-as alias.
GMAIL_SEND_FROM = os.environ.get('GMAIL_SEND_FROM', '').strip()
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'david@dad4dogs.ca')
# UID host for booking .ics invites (stable per visit for future updates/cancels).
ICAL_UID_DOMAIN = os.environ.get('ICAL_UID_DOMAIN', 'dad4dogs.local')
# iCal ORGANIZER name/email and LOCATION come from Business Settings (/settings/).
# Optional client-facing link embedded in calendar DESCRIPTION (empty = omit).
BOOKING_CLIENT_NOTES_URL = os.environ.get('BOOKING_CLIENT_NOTES_URL', 'https://dad4dogs.ca/dash/').strip()

# GPS fallback for timeline events when device geolocation is unavailable.
BUSINESS_FALLBACK_LATITUDE = float(os.environ.get('BUSINESS_FALLBACK_LATITUDE', '43.002700'))
BUSINESS_FALLBACK_LONGITUDE = float(os.environ.get('BUSINESS_FALLBACK_LONGITUDE', '-81.228400'))
TIMELINE_VIDEO_MAX_BYTES = 25 * 1024 * 1024
TIMELINE_THUMBNAIL_MAX_PX = 800
