# Generated by Django 5.2.14 on 2026-07-05 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='coi_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='coi_confirmed_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='coi_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papers_received', models.BooleanField(default=True)),
                ('received_at', models.DateField(default=django.utils.timezone.localdate)),
                ('validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('vet_clinic', models.CharField(blank=True, max_length=200)),
                ('vaccination_details', models.TextField(blank=True, help_text='Rabies, kennel cough, expiry dates, etc.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='operations.clientprofile')),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
    ]
