# Generated by Django 5.2.14 on 2026-07-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_owner_coi_and_vax_expiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsAppExport',
        ),
    ]
