# Generated by Django 5.2.14 on 2026-07-05 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_whatsapp_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='series_position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-based index within the repeat series.', null=True),
        ),
        migrations.CreateModel(
            name='VisitSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=20)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('end_type', models.CharField(max_length=10)),
                ('total_occurrences', models.PositiveSmallIntegerField()),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('anchor_start', models.DateTimeField(help_text='Start of the first occurrence (template for the series).')),
                ('anchor_end', models.DateTimeField(help_text='End of the first occurrence (template for the series).')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_series', to='operations.clientprofile')),
            ],
            options={
                'verbose_name_plural': 'visit series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='operations.visitseries'),
        ),
    ]
