# Generated by Django 5.2.14 on 2026-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_visit_confirmation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='X', editable=False, max_length=1, unique=True)),
                ('business_name', models.CharField(default='Dad4dogs', max_length=200)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, help_text='Full mailing or service address.')),
                ('hours_of_operation', models.TextField(blank=True, help_text='When clients can reach you or drop off/pick up.')),
                ('main_phone', models.CharField(blank=True, max_length=30)),
                ('secondary_phone', models.CharField(blank=True, help_text='Alternate line (e.g. secondary mobile).', max_length=30)),
                ('emergency_phone', models.CharField(blank=True, help_text='Number clients should call if there is an urgent problem.', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business profile',
                'verbose_name_plural': 'business profile',
            },
        ),
    ]
