# Generated by Django 5.2.14 on 2026-07-06 14:21

import django.db.models.deletion
import operations.models.scheduling
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_business_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Service address; used as LOCATION on calendar invites.'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Organizer email on calendar invites — should match your Gmail send-as address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(default='Dad4dogs', help_text='Display name on calendar invites (ORGANIZER CN=).', max_length=200),
        ),
        migrations.CreateModel(
            name='VisitTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('photo_high_res', models.ImageField(blank=True, help_text='Uncompressed master image for customer printing.', upload_to=operations.models.scheduling.timeline_upload_path)),
                ('photo_thumbnail', models.ImageField(blank=True, help_text='Web-optimized WebP thumbnail for timeline display.', upload_to=operations.models.scheduling.timeline_upload_path)),
                ('video_file', models.FileField(blank=True, help_text='Gallery-selected video (no live capture).', upload_to=operations.models.scheduling.timeline_upload_path)),
                ('caption_notes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_used_fallback', models.BooleanField(default=False, help_text='True when device GPS was unavailable and site fallback was applied.')),
                ('location_fallback_label', models.CharField(blank=True, help_text='Business address used when GPS fallback was applied.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='operations.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
