# Generated by Django 5.2.14 on 2026-07-06 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_shared_media_share_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedaccesslog',
            new_name='operations__client__17dcdd_idx',
            old_name='operations__client__8d2f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='feedaccesslog',
            new_name='operations__client__3414ae_idx',
            old_name='operations__client__f0a2c1_idx',
        ),
    ]
