# Generated by Django 5.2.14 on 2026-08-23 23:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_owner_emergency_and_vet_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinemediaasset',
            name='captured_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Exact capture/upload time — preserved when forwarded.'),
        ),
    ]
