# Generated by Django 5.2.14 on 2026-08-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_timeline_media_asset_captured_at_default'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['scheduled_start'], name='visit_scheduled_start_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['scheduled_end'], name='visit_scheduled_end_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status'], name='visit_status_idx'),
        ),
    ]
