# Generated by Django 5.2.14 on 2026-08-27 18:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_multi_tenant_workspace_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100)),
                ('target_category', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('SMALL_PET', 'Small pet'), ('PROPERTY_ONLY', 'Property only')], default='DOG', max_length=20)),
                ('rate_type', models.CharField(choices=[('FLAT', 'Flat'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily')], default='FLAT', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive services are hidden from booking dropdowns (soft-hide).')),
                ('capacity_exempt', models.BooleanField(default=False, help_text='If True, future bookings skip facility capacity checks (Phase 2 wiring).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='operations.workspace')),
            ],
            options={
                'ordering': ['target_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBehaviorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('DURATION_UNDER', 'Duration under (hours)'), ('DURATION_OVER', 'Duration over (hours)'), ('TIME_WINDOW', 'Time window')], max_length=20)),
                ('threshold_value', models.PositiveIntegerField(help_text='Hours or time-window parameter depending on trigger_type.')),
                ('modified_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_rules', to='operations.businessservice')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='operations.workspace')),
            ],
            options={
                'ordering': ['trigger_type', 'threshold_value'],
            },
        ),
        migrations.AddConstraint(
            model_name='businessservice',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_tenant_business_service_slug'),
        ),
    ]
