# Generated by Django 5.2.14 on 2026-08-27 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_businessservice_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='business_service',
            field=models.ForeignKey(blank=True, help_text='Catalog offering for this stay. Required on new bookings; null on legacy visits.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='operations.businessservice'),
        ),
    ]
