# Generated by Django 5.2.14 on 2026-08-29 17:54

from django.db import migrations, models


def backfill_passed_meet_greets(apps, schema_editor):
    """Dogs already past M&G into Evaluation+ get outcome=pass on completed M&G visits."""
    ClientProfile = apps.get_model('operations', 'ClientProfile')
    Visit = apps.get_model('operations', 'Visit')
    past_stages = ('evaluation', 'approved')
    for dog in ClientProfile.objects.filter(pipeline_stage__in=past_stages):
        Visit.objects.filter(
            client=dog,
            status='completed',
            business_service__slug='meet_greet',
            meet_greet_outcome='',
        ).update(
            meet_greet_outcome='pass',
            meet_greet_notes='Backfilled: pipeline already past Meet & Greet.',
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_visit_evaluation_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='meet_greet_notes',
            field=models.TextField(blank=True, help_text='Notes from the Meet & Greet (suitability / decline reason).'),
        ),
        migrations.AddField(
            model_name='visit',
            name='meet_greet_outcome',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('decline', 'Decline')], help_text='Set after Meet & Greet check-out (pass / decline).', max_length=20),
        ),
        migrations.RunPython(backfill_passed_meet_greets, noop_reverse),
    ]
