# Generated by Django 5.2.14 on 2026-09-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_visit_meet_greet_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='calendar_invite_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the last ICS REQUEST/CANCEL email was sent.', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='calendar_invite_state',
            field=models.CharField(choices=[('none', 'None'), ('awaiting_confirm', 'Awaiting client confirm'), ('invite_issued', 'Calendar invite issued'), ('awaiting_change_confirm', 'Awaiting change confirm'), ('cancelled_invite', 'Calendar invite cancelled')], default='none', help_text='Client calendar invite lifecycle (orthogonal to Visit.status).', max_length=32),
        ),
        migrations.AddField(
            model_name='visit',
            name='calendar_manage_token',
            field=models.CharField(blank=True, help_text='Capability token for the public booking manage URL.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='calendar_review_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the last review/confirm link email (no ICS) was sent.', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='ics_sequence',
            field=models.PositiveIntegerField(default=0, help_text='Last SEQUENCE value included in an outbound ICS payload.'),
        ),
        migrations.AddField(
            model_name='visit',
            name='ics_uid',
            field=models.CharField(blank=True, help_text='Stable iCalendar UID for this visit’s outbound invites.', max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Legacy: when a booking confirmation email was sent. Prefer calendar_review_sent_at / calendar_invite_sent_at.', null=True),
        ),
    ]
