# Generated by Django 5.2.14 on 2026-09-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_visit_calendar_invite_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='timezone',
            field=models.CharField(choices=[('America/St_Johns', "Newfoundland Time (St. John's)"), ('America/Halifax', 'Atlantic Time (Halifax)'), ('America/Toronto', 'Eastern Time (Toronto)'), ('America/Winnipeg', 'Central Time (Winnipeg)'), ('America/Edmonton', 'Mountain Time (Calgary / Edmonton)'), ('America/Vancouver', 'Pacific Time (Vancouver)')], default='America/Toronto', help_text='Local timezone for this business. Booking times you enter use this zone.', max_length=64),
        ),
    ]
