# Generated by Django 5.2.14 on 2026-09-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_businessprofile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='timezone',
            field=models.CharField(default='America/Toronto', help_text='IANA timezone where this business operates (not server location). Independent of the address field. Booking times use this zone. Catalog: operations.services.business_timezones.', max_length=64),
        ),
    ]
